apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: vclip
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/s4njee/vclip.git'
    targetRevision: HEAD
    path: k8s
  destination:
    server: 'https://kubernetes.default.svc' # Target cluster URL
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
